#!/usr/bin/env bash

date 
git status
git add .
git commit -am $1 && 
git status 
git push &&
git status
date 

#date && git status && git add . && git commit -am "" && git status && git push && git status && date && date
