#!/usr/bin/env bash
echo ''
date && 
echo ''
echo '     Git Update and Push'
echo ''
git status &&
echo ''
git add . &&
echo ''
git commit -am $1 &&
echo ''
git status &&
echo ''
git push &&
echo ''
git status &&
echo ''
echo '     Git Update and Push'
echo ''
date &&
echo ''
